application.api.baseUrl=https://jsonplaceholder.typicode.com
application.ui.baseUrl=https://reqres.in
application.ui.waitTimeOut=30
application.env=qa
application.auth.baseUrl=https://practicetestautomation.com
application.auth.username=student
application.auth.password=Password123
automation.browser=chrome
